### ISSUE TITLE
Handle edge cases of movement

### ISSUE THREAD

**Issue by fjebaker** [fjebaker/global-game-jam-2023#12]
* What should happen when player presses multiple input keys at once?
* How should the "camera" track the player?
  * Keep the player centered at all times?
  * Classic Zelda style? [Move around freely on current screen; scroll when player hits the edge]
  * Keep the player in some inset region of the screen, and move the map when the player is "pushing" on the edge of that inset?

**Comment by jwiggins** [comment]
Currently sticking with "Keep the player centered at all times"

Perhaps on Sunday we can try to make this nicer, but it gets a bit fiddly between tile coords and pixel coords.
