### ISSUE TITLE
Implement the retrievables mission system

### ISSUE THREAD

**Issue by JR-Mitchell** [fjebaker/global-game-jam-2023#2]
### Acceptance Criteria
The gameplay loop should go as follows:
- You talk to the rabbit character, who requests one of the retrievable items
- You dig down through the ground to find and collect the given items
- You bring the items back up to the rabbit, and return to the head of the gameplay loop

### Technical details / questions
- How do you know where the items are? An indicator?
- When you collect them, where do they go? Inventory slot(s)?

### Dependencies
Relies on the following being done:
- Create assets for the retrievable items
- Implement player interaction (movement and eating)
- Create asset for the speech bubble

**Comment by jwiggins** [comment]
This is done!
