### ISSUE TITLE
Eating mechanic

### ISSUE THREAD

**Issue by fjebaker** [fjebaker/global-game-jam-2023#20]
- #19 
- [x] eat a dirt block
- [ ] animations / sfx
- #10 

Eating should take approximately 30 frames before block destroyed.

**Comment by JR-Mitchell** [comment]
@fjebaker @jwiggins is this closed now - can eating animations be a stretch goal?

**Comment by jwiggins** [comment]
I'm fine with the animation being a stretch goal
