### ISSUE TITLE
Implement timing logic for rabbit health

### ISSUE THREAD

**Issue by jwiggins** [fjebaker/global-game-jam-2023#56]
### Acceptance criteria
- As time progresses, the rabbit becomes more unwell
- Bringing the rabbit items makes the rabbit more well
- The wellness of the rabbit is indicated by the sprite used by it

### Dependencies
Requires the following tickets to be done:
- Create assets for the rabbit

**Comment by jwiggins** [comment]
@fjebaker I think this is all done, no?

**Comment by JR-Mitchell** [comment]
Yes this is done
